# Generated by Django 4.1 on 2023-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_hydjobs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bngjobs',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='company',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='eligibility',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='company',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='eligibility',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='company',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='eligibility',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
